apiVersion: v1
kind: Pod
metadata:
   name: my-app-pod

spec:
  containers:
  - name: fun-frontend
    image: funny-frontend:0.1
    ports:
    - containerPort: 80
  - name: funny-backend
    image: funny-backend:0.1
    ports:
    - containerPort: 8000
