name: funny-app-dev
description: A minimal AWS Python Pulumi program
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
  funny-app-dev:resourceOwner: yohansdemisie@gmail.com
  funny-app-dev:appName: funny-app
  funny-app-dev:env: dev
